version: '3.8'

services:
  app:
    build:
      context: . # same as WORKDIR from Dockerfile
    restart: always
    expose:
      - 5000
    environment:
      - FLASK_APP=/src/aca/api/access_control_api.py
      - FLASK_ENV=production

  nginx:
    image: nginx:1.25.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl_certificates:/etc/nginx/ssl  # Mount SSL certificate files
    depends_on:
      - app